std_msgs/Header header

float32[3] position_ned_m
float32[3] velocity_ned_mps
bool active
bool hit

float32 thrust_n
float32 length_m
float32 fin_pitch_rad
float32 fin_yaw_rad
float32 fin_roll_rad
bool seeker_locked
float32 seeker_fov_azimuth_rad
float32 seeker_range_m

float32 attitude_w
float32 attitude_x
float32 attitude_y
float32 attitude_z
float32 pitch_rate_rps
float32 yaw_rate_rps
float32 roll_rate_rps
